theme: minima 
#remote_theme: jekyll/minima
#plugins:
#  - jekyll-remote-theme
title: maUIRL
description: Use Inspired Many-Agent Reinforcement Learning
header_pages:
  - application.md
  - methods.md
  - code.md
  - tutorial.md
minima:
  skin: dark
